### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by trebmuh** [blablack/deteriorate-lv2#5]
Bonjour blablack.

J'ai tenté une construction à partir des sources du GIT qui a planté. Par acquis de conscience, j'ai tenté une construction à partir du paquet de ton PPA sur un système Debian Jessie (à jour).

J'ai une erreur dans les deux cas au niveau du configure qui me dit :
```
Checking for 'lvtk-plugin-2' >= 2.0.0    : not found 
The configuration failed
```
En regardant dans le `build/config.log `, il me dit :
```
Checking for 'lvtk-plugin-2' >= 2.0.0
['/usr/bin/pkg-config', '--atleast-version=2.0.0', 'lvtk-plugin-2']
not found
```
le paquet lvtk-dev est installé sur mon système, c'est la version "Jessie" : https://packages.debian.org/search?keywords=lvtk-dev

Aurais-tu une idée de ce qui pourrait clocher ici par hasard ?

**Comment by blablack** [comment]
Il faut la version 2.0 minimum de lvtk.

D'apres le lien que tu m'as envoyé, il semblerait que Jessie ai uniquement 1.2.0.

**Comment by trebmuh** [comment]
OK, avec la version 2.0, ça passe bien mieux. Merci.
