### ISSUE TITLE
Tag/Release 1.0.6 doesn't have a v in front of it

### ISSUE THREAD

**Issue by simonvanderveldt** [blablack/deteriorate-lv2#6]
Hi Aurelien, first of all thanks for the awesome plugin! Really liking it!
It's a bit of a stupid subject, but the 1.0.6 release doesn't have a `v` in front of it like the other releases. Can you maybe add it?

I ran into this because I run a small script against GitHub's API every 24h that checks if there are new releases for projects I have created an ebuild (Gentoo package definition) for. And apparently GitHub's API actually sorts alphabetically, not based on date, so it didn't pick up the 1.0.6 release :|

Just wanted to let you know, feel free to do whatever you want with this ;)

**Comment by blablack** [comment]
I updated it - may as well keep the version convention correct! thanks
