### ISSUE TITLE
Tag/Release 1.0.7 doesn't have a v in front of it

### ISSUE THREAD

**Issue by simonvanderveldt** [blablack/deteriorate-lv2#9]
:wave: Kind of deja-vu :P but same as #6 the 1.0.7 release is missing the v in front of it just like last time :grimacing: 
Could you add a tag with a v in front? Or are you going to version without the v in front from now on?
Then I can update the package I'm maintaining to not include the v in front of the version :)

**Comment by simonvanderveldt** [comment]
Quick ping/reminder about this

**Comment by blablack** [comment]
Sorry about the delay - this is corrected now.

**Comment by dvzrv** [comment]
Hi! I'm packaging this for Arch Linux.

We now have two different types of tags in this repository (and I have been using the one without the `v` prefix).
For future reference it would be great to stick with one and remove the other altogether.
Thanks! :)

**Comment by dvzrv** [comment]
@blablack that being said: I can use whichever tagging style as long as it is consistent! :)

**Comment by simonvanderveldt** [comment]
@dvzrv Those differences were also my issue :)
:crossed_fingers: for the future

**Comment by blablack** [comment]
They should all have consistent tag now...
